lang: en-US
title: My Awesome Site

#  Pagination - https://jekyllrb.com/docs/pagination/
# paginate: 10
# paginate_path: /page:num/

plugins: # previsously gems
  # - jekyll-feed
  # - jekyll-seo-tag
  # - jekyll-sitemap
  - jekyll-paginate


defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
      